
.. note::
    このチュートリアルは、クリエイティブ・コモンズ・ライセンス 表示 - 継承 3.0 非移植 (CC BY-SA 3.0) のもとでライセンスされています。
    翻訳の元にしたオリジナルはこちらです。 `Symfony2 Jobeet`  http://www.intelligentbee.com/blog/tag/symfony2-jobeet/.

[![Creative Commons License][image-1]][1]
This work is licensed under a [Creative Commons Attribution 3.0 Unported License][1].

[1]:    http://creativecommons.org/licenses/by/3.0/deed.en_US

[image-1]:  http://i.creativecommons.org/l/by/3.0/80x15.png
