.. note::

   .. image:: http://i.creativecommons.org/l/by-sa/3.0/88x31.png
      :alt: Creative Commons License
      :align: left
      :target: http://creativecommons.org/licenses/by-sa/3.0/deed.ja

   This work is licensed under a Creative Commons Attribution-ShareAlike 3.0 Unported License.
   original `symfony2 jobeet` article is here http://www.intelligentbee.com/blog/tag/symfony2-jobeet/.